"""followers

Revision ID: 925076798e92
Revises: 5f1d1bf06bad
Create Date: 2019-02-19 16:17:58.730866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925076798e92'
down_revision = '5f1d1bf06bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
